In [1]:
!pip install ultralytics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 48.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 33.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 31.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 59.1 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling 

In [ ]:
import gradio as gr
from ultralytics import YOLO # Importamos la clase YOLO de ultralytics
from IPython.display import Image, display
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 1. Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Ajusta la ruta a tu modelo entrenado en Google Drive
# Asegúrate de que esta ruta sea correcta y que el archivo .pt exista.
MODEL_PATH = '/content/drive/MyDrive/tp_integrador/best.pt' # CAMBIA ESTO POR LA RUTA DE TU MODELO YOLOv8

# 3. Cargar el modelo YOLOv8
try:
    model = YOLO(MODEL_PATH) # Cargar el modelo YOLOv8
    print("Modelo YOLOv8 cargado exitosamente.")
except Exception as e:
    print(f"Error al cargar el modelo: {e}")
    print("Asegúrate de que la ruta al modelo sea correcta y que el archivo best.pt exista.")
    print("También verifica que la librería 'ultralytics' esté instalada correctamente.")

# 4. Crear la función de inferencia
def detect_characters_yolov8(image):
    if image is None:
        return "No se ha cargado ninguna imagen."
    img = np.array(image)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (240, 240))
    image = img.astype(np.uint8)

    # Realizar la inferencia con YOLOv8
    # source=image le pasa la imagen directamente al modelo
    # conf=0.25 (opcional): umbral de confianza para las detecciones
    # iou=0.7 (opcional): umbral de Intersection Over Union para Non-Maximum Suppression (NMS)
    results = model(source=image, conf=0.1, iou=0.01, save=False, show=False)
    print(format(results))

    # Procesar los resultados y dibujar las cajas
    # YOLOv8 devuelve una lista de objetos Results, uno por cada imagen procesada.
    # Si procesamos una sola imagen, el primer elemento (results[0]) es el relevante.
    for r in results:
        # r.plot() dibuja las cajas y etiquetas en la imagen.
        # Devuelve un arreglo NumPy de la imagen con las detecciones.
        im_bgr = r.plot()
        plt.imshow(im_bgr)
        plt.show()
        # Gradio espera imágenes en formato RGB, r.plot() devuelve BGR por defecto.
        # Convertimos de BGR a RGB.
        im_rgb = im_bgr[..., ::-1]
        return im_rgb

    return "No se detectaron caracteres o hubo un problema al procesar."


# 5. Configurar la interfaz Gradio
iface = gr.Interface(
    fn=detect_characters_yolov8,
    inputs=gr.Image(type="pil", label="Cargar Imagen"),
    outputs=gr.Image(type="numpy", label="Detecciones"),
    title="Detector de Caracteres con YOLOv8",
    description="Carga una imagen para detectar caracteres usando un modelo YOLOv8."
)

# Lanzar la interfaz Gradio
if __name__ == "__main__":
    iface.launch(debug=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Modelo YOLOv8 cargado exitosamente.
It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://2706ae9f8401ca38bc.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)



0: 256x256 1 A, 1 G, 1 H, 1 K, 15 Ms, 8 Ns, 1 Q, 1 S, 1 U, 1 V, 2 Ws, 2 gs, 2 js, 1 m, 1 5, 77.5ms
Speed: 2.8ms preprocess, 77.5ms inference, 1.4ms postprocess per image at shape (1, 3, 256, 256)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L', 12: 'M', 13: 'N', 14: 'O', 15: 'P', 16: 'Q', 17: 'R', 18: 'S', 19: 'T', 20: 'U', 21: 'V', 22: 'W', 23: 'X', 24: 'Y', 25: 'Z', 26: 'a', 27: 'b', 28: 'c', 29: 'd', 30: 'e', 31: 'f', 32: 'g', 33: 'h', 34: 'i', 35: 'j', 36: 'k', 37: 'l', 38: 'm', 39: 'n', 40: 'o', 41: 'p', 42: 'q', 43: 'r', 44: 's', 45: 't', 46: 'u', 47: 'v', 48: 'w', 49: 'x', 50: 'y', 51: 'z', 52: '0', 53: '1', 54: '2', 55: '3', 56: '4', 57: '5', 58: '6', 59: '7', 60: '8', 61: '9'}
obb: None
orig_img: array([[[253, 252, 253],
        [242, 241, 241],
        [251, 255, 254],
        ...,
   

In [7]:
from ultralytics import YOLO # Importamos la clase YOLO de ultralytics
from IPython.display import Image, display
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 1. Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Ajusta la ruta a tu modelo entrenado en Google Drive
# Asegúrate de que esta ruta sea correcta y que el archivo .pt exista.
MODEL_PATH = '/content/drive/MyDrive/tp_integrador/best.pt' # CAMBIA ESTO POR LA RUTA DE TU MODELO YOLOv8

# 3. Cargar el modelo YOLOv8
try:
    model = YOLO(MODEL_PATH) # Cargar el modelo YOLOv8
    print("Modelo YOLOv8 cargado exitosamente.")
except Exception as e:
    print(f"Error al cargar el modelo: {e}")
    print("Asegúrate de que la ruta al modelo sea correcta y que el archivo best.pt exista.")
    print("También verifica que la librería 'ultralytics' esté instalada correctamente.")

imagen = cv2.imread('/content/BOMBEROS.jpg')
results = model.predict(source=imagen, conf=0.5, save=False)
for r in results:
    # r.boxes es un objeto Boxes
    # Para acceder a los datos de los bounding boxes (xyxy, xywh, conf, cls)

    # Opción 1: Convertir a un arreglo de NumPy (más común y eficiente)
    # r.boxes.xyxy - Coordenadas [x1, y1, x2, y2]
    # r.boxes.xywh - Coordenadas [x_centro, y_centro, ancho, alto]
    # r.boxes.conf - Puntajes de confianza
    # r.boxes.cls - IDs de clase
    print(r.boxes.xyxy)
    print(r.boxes.conf)
    print(r.boxes.cls)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Modelo YOLOv8 cargado exitosamente.

0: 256x256 7 Ms, 75.2ms
Speed: 1.6ms preprocess, 75.2ms inference, 1.3ms postprocess per image at shape (1, 3, 256, 256)
tensor([[ 57.9628,  90.2903,  81.4366, 109.1802],
        [126.7653, 105.0409, 145.5069, 125.4711],
        [126.1200, 107.9269, 142.7892, 124.6785],
        [123.8098, 111.4428, 141.5633, 126.6412],
        [ 57.7204,  89.3934,  83.7174, 105.2890],
        [194.1206, 107.3236, 211.7421, 125.6137],
        [126.8438, 111.7157, 144.6666, 126.9387]])
tensor([0.7720, 0.7385, 0.6729, 0.6265, 0.6125, 0.5530, 0.5104])
tensor([12., 12., 12., 12., 12., 12., 12.])
